---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-added-large-files
  - id: debug-statements
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v15.0.7'
  hooks:
  - id: clang-format
    exclude: "^(dune/xt/test/gtest/|pybind11)"
- repo: https://github.com/google/yamlfmt
  rev: v0.16.0
  hooks:
  - id: yamlfmt
    exclude: ".clang-format|.clang-tidy"
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: 'v0.6.13'
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml>=5.1] # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    exclude: "config.h.cmake|pybind11"
    args: ["-i", "--config-files=.cmake_format.py"]
  - id: cmake-lint
    additional_dependencies: [pyyaml>=5.1] # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    exclude: "config.h.cmake|pybind11"
    args: ["--config-files=.cmake_format.py"]
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
  - id: check-github-actions
    additional_dependencies:
    - pip_system_certs==4.0
  - id: check-dependabot
    additional_dependencies:
    - pip_system_certs==4.0
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.7.7.23
  hooks:
  - id: actionlint
    additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
