---
name: Dump workspace
description: Dumps and uplaods the current state of the workspace to be loaded by the load_workspace action
inputs:
  artifact_name:
    description: Passed on as `name` to actions/upload-artifact
    required: true
outputs:
  artifact-id:
    description: Passed on from actions/upload-artifact
    value: steps.upload.artifact-id
  artifact-url:
    description: Passed on from actions/upload-artifact
    value: steps.upload.artifact-url
  artifact-digest:
    description: Passed on from actions/upload-artifact
    value: steps.upload.artifact-digest
runs:
  using: composite
  steps:
  # We're seeing issues with using actions/{upload,download}-artifact directly:
  # - file permissions are not taken into account
  # - unpacking archives with many files fails
  # We thus tar ourselves before/after.

  - id: prep_workspace
    shell: bash -elo pipefail {0}
    run: |
      : Prepare workspace for upload
      echo "Ensuring workspace folder coincides with repo name"
      export REPO_NAME="${GITHUB_REPOSITORY#*/}"
      [[ "ENSURE_REPO_NAME_IS_NOT_EMPTY${REPO_NAME}" == "ENSURE_REPO_NAME_IS_NOT_EMPTY" ]] && exit 1
      cd "${{github.workspace}}"
      cd ..
      [[ -e "${REPO_NAME}" ]] || exit 1

      echo "Compressing workspace"
      export TAR_NAME="${REPO_NAME}.tgz"
      tar -czf "${TAR_NAME}" "${REPO_NAME:?}"/* "${REPO_NAME:?}"/.??*
      mv "${TAR_NAME}" "${REPO_NAME}/"

      echo "Storing state information to be re-used by load action"
      cd "${{github.workspace}}"
      echo "${REPO_NAME}" > dump_workspace.REPO_NAME
      echo "${TAR_NAME}" > dump_workspace.TAR_NAME

      [[ -e "${TAR_NAME}" ]] || exit 1
      echo "path=${TAR_NAME}" >> "${GITHUB_OUTPUT}"

  - name: Upload workspace
    id: upload
    uses: actions/upload-artifact@v4.6.1
    with:
      name: ${{inputs.artifact_name}}
      path: |
        ${{steps.prep_workspace.outputs.path}}
        dump_workspace.REPO_NAME
        dump_workspace.TAR_NAME
      compression-level: 0
      if-no-files-found: error
