---
name: Non-docker Build and Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# Add concurrency to cancel in-progress jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-tags: true
        fetch-depth: 0

    - name: Restore build cache
      uses: actions/cache/restore@v3
      with:
        path: build
        key: ${{ runner.os }}-build

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Configure CMake
      id: configure_cmake
      run: cmake --preset=debug

    - name: Build
      run: cmake --build --preset=debug --parallel

    - name: Build test binaries
      run: |
        cmake --build --preset=debug --target test_binaries --parallel

    - name: Test with CTest
      run: |
        ctest --preset=debug

    - name: Save build cache
      if: ${{ success() && steps.configure_cmake.outcome == 'success' }}
      uses: actions/cache/save@v3
      with:
        path: build
        key: ${{ runner.os }}-build

    - name: Upload error logs (in case of failure)
      if: always() && (steps.configure_cmake.conclusion == 'failure')
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: linux_vcpkg_error-log
        path: |
          ${{ github.workspace }}/build/*/vcpkg-*.log
          ${{ github.workspace }}/.vcpkg-root/buildtrees/*/*.log
