---
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
    - main # The 'main' branch
    - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }} # to check out the actual pull request commit, not the merge commit
        fetch-depth: 0 # a full history is required for pull request analysis
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Configure CMake
      id: configure_cmake
      run: cmake --preset=debug

    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2024.3
      with:
        pr-mode: false
        args: --compile-commands build/debug/compile_commands.json
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_526821687 }}
        QODANA_ENDPOINT: 'https://qodana.cloud'
